language: rust
dist: xenial

matrix:
  include:
    - rust: stable
      env: MODE='BUILD'

    - rust: beta
      env: MODE='BUILD'

    - rust: nightly
      env: MODE='BUILD'

    - rust: stable
      env: MODE='TESTS' RUST_BACKTRACE='1' RUST_LOG='eventstore=debug'

      before_script:
        - docker pull eventstore/eventstore:latest
        - docker run -p 1113:1113 -p 2113:2113 -d eventstore/eventstore:latest

      script:
        - cargo test

    - rust: stable
      env: MODE='LINTING'

      before_script:
        - rustup component add clippy-preview

      script:
        - cargo clippy -- -D warnings

  allow_failures:
    - rust: nightly
    - env: MODE='LINTING'

  fast_finish: true

script:
  - cargo check

deploy:
  provider: cargo
  on:
    tags: true
    condition: "$MODE = TESTS"
  token:
    secure: u3rEfYcCWk1GeB3fZVlW/TDForpMS866+IsUGmGJZAbKwjaNBjR8JUdOl/UeAsqHnq5H+oFDrXSBjnbnqIsgVBbS3fdS9hpuUXioWQQgwm5sr+xbi/uKaBcKnaErfy8KEH5vkqJpsv5O/u4duhCPBNFg8tM+MQRh33MRTXPA5aNNx5mdJ0VHKP+ZUwL1PkprfwRiwleCBVJ4mhJ5zvSwgenLjzZG89YtTCUiyGrqyK8jryfX8hHrV3QNBFQrelNafmgXnwcUPjw/BxIytQY1wlauX3t+Z/wp0+Iftt/qK+K9xHBpIrAKL8YGxGYmglUX0WTjVKr8i6J00QRmILr9lQMb0TUQqGEnU0ozMx3b6vPKGsu5H/R4RtanHvDa9z7KAN5dA7b6HqIBexXWmE6mtEpP9p278ojYRfcEpH7AQPDdU8CkM+ZK8+qW4jZuaM7GyHOiTYdGtP1PtGHsUmfM5MaATW0lGZQUNQbDwRlyjYipuyqdy4dJyBOw755iBylLsfJMLet9eBia+jYT/ndb1vaLZgs5to683CObRcdeaQDRbvcmfb72IsE2CE8w298a08ZWEYg/GG1k746dW56aRTXqEsLuL/7PhudTzb7cWhm1rRLhc5t2CT3/Rtd4tWtXrT/bw8e2WUuyDmzAy7qklmooBzG2jDZixV2uV4IFAKY=

cache: cargo
