[package]
name = "eventstore"
version = "0.1.0"
authors = ["Yorick Laupa <yo.eight@gmail.com>"]

[dependencies]
tokio-core = "0.1.10"
tokio-io = "0.1.3"
futures = "0.1.17"
uuid = { version  = "0.5.1", features = [ "v4" ] }
bytes = "0.4.5"
