[package]
name = "eventstore"
version = "0.1.0"
authors = ["Yorick Laupa <yo.eight@gmail.com>"]
build = "build.rs"

[dependencies]
tokio-core = "0.1.10"
tokio-io = "0.1.3"
futures = "0.1.17"
uuid = { version  = "0.5.1", features = [ "v4" ] }
bytes = "0.4.5"
chan = "0.1.19"
chrono = "0.4.0"
timer = "0.2.0"
time = "0.1.38"
protobuf = "1.4.3"

[build-dependencies]
protoc-rust = "1.4"
