[package]
name = "eventstore"
version = "0.1.0"
authors = ["Yorick Laupa <yo.eight@gmail.com>"]
build = "build.rs"

[dependencies]
tokio = "0.1.1"
tokio-core = "0.1.10"
tokio-io = "0.1.3"
futures = "0.1.17"
uuid = { version  = "0.5.1", features = [ "v4" ] }
bytes = "0.4.5"
timer = "0.2.0"
time = "0.1.38"
protobuf = "1.4.3"
tokio-timer = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
# log = "0.4.1"

[build-dependencies]
protoc-rust = "1.4"
